### PR TITLE
Don't use OWM data if using sensor.

### PR DESCRIPTION
**Pull request by omenek159**
If we set sensor to provide some data then we want to drop those data from OWM to not mix each other. Additionally if sensor didn't provide data for whole period then we set it to 0.

### CODE REVIEW

**Comment by jeroenterheerdt** [comment]
not sure what you're trying to do. AFAIK this mixing should already not happen - also keep in mind that if someone switches from OWM to sensors or vice versa in between calculation moments we cannot simply drop that weather data.
Also setting data to 0 is not correct as it might potentially screw up aggregates

**Comment by omenek159** [comment]
I just updated to 2024.7.4 and no, it doesn't work like that so my idea behind this PR is still valid. Here you have my config and logs so you can see that OWM is still taken into calculation. 

[si_agg.txt](https://github.com/user-attachments/files/16172574/si_agg.txt)
[si_agg2.txt](https://github.com/user-attachments/files/16172575/si_agg2.txt)

But you're right about dropping OWM data and setting to 0, but that was first solution that comes into my mind.

**Comment by omenek159** [comment]
Please remove this PR. Looks like 2024.7.10 fixed issue. The only problem I noticed is if sensor is unavailable (for example at ha start) owm value is saved.

**Comment by jeroenterheerdt** [comment]
@omenek159 feel free to open a new PR for that issue then, I will open an issue to track it.

**Pull request closed without merging**
