### PR TITLE
Added SOLRAD_behavior EstimateFromMean

### PR DESCRIPTION
**Pull request by tefracky**
Added a new possibility to calclate the solrad value. It is the mean value of the sun hours and the temperature and called EstimateFromMean. It shoult improve the accuracy of a calculated solrad value.

### CODE REVIEW

**Comment by jeroenterheerdt** [comment]
I love this, but the name is not good. Please add a better name instead of EstimateFromMean.

**Comment by tefracky** [comment]
I am not a native English speaker, so do you have any suggestions?

**Comment by jeroenterheerdt** [comment]
neither am I, but since it's taking the average of the sunhours and the temperature, I'd propose something like EstimateFromSunHoursAndTemperature. Of course, update the descriptions in the language files as well.

For context, at first I was going to close this because it seemed to do exactly what EstimateFromTemp does, but only after looking at the code I realized that is actually not what it does. Imagine the confusion ti the user or future developer if we don't give things good names.

**Comment by tefracky** [comment]
It's done. I also fixed some markdown formatting in the Readme (tailing whitepaces and missing blank lines).

**Review by jeroenterheerdt — APPROVED** [review]

**Pull request merged**
